"""Pin the pre-hybrid /api/search ordering so ?retriever=clip stays
byte-for-byte identical now that the hybrid pipeline has landed.

The snapshot file was generated by running this test with
``UPDATE_HYBRID_SNAPSHOT=1`` once against the pure-CLIP route, then
committed. On every subsequent run the test loads the snapshot and asserts
the current ordering still matches, so ``?retriever=clip`` keeps reproducing
the legacy ranking.

Environment caveat: this test does *not* use the hermetic ``tmp_config``
fixture — the snapshot is meaningful only against a real indexed library.
On CI / fresh checkouts the test SKIPs cleanly.

Scoped to ONE film (``?film=jeca_tatu_1959``) on purpose. Without a
``film`` param ``/api/search`` runs the cross-film aggregate, whose global
ranking is re-shuffled by *any* library change — registering a new film or
re-embedding an existing one invalidated the snapshot wholesale (it was
re-pinned four times between 2026-05-23 and 2026-06-07 for exactly that
reason, each time with zero overlap rather than a small drift). Pinning a
single film means only that film's own index can move the ordering, so a
failure here points at retrieval behaviour instead of corpus composition.

Consequence: the skip guard checks for *this* film specifically, not for
"any indexed film" — on a machine with a different library the test must
bow out rather than fail.
"""

from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from api.deps import get_config
from api.server import app

logger = logging.getLogger(__name__)

SNAPSHOT_PATH: Path = Path(__file__).parent / "fixtures" / "hybrid_search_regression.json"

# The single film this snapshot is pinned against. Changing it invalidates
# the fixture — regenerate with UPDATE_HYBRID_SNAPSHOT=1 in the same commit.
SNAPSHOT_FILM = "jeca_tatu_1959"

# Queries chosen to cover three behavior buckets:
#  - semantic-strong (CLIP should excel)
#  - literal numeric (BM25 should win under hybrid)
#  - generic (broad query, deep ranking matters)
# The route default has since flipped to ``retriever=hybrid``, so calling
# ``/api/search?q=...`` now returns hybrid-fused output. The snapshot was
# captured against the earlier pure-CLIP path, so we pin ``retriever=clip``
# explicitly here. With ``?film=`` set this reaches the per-film
# ``search_text`` branch in ``api.services.search`` (``retriever == "clip"``),
# which never consults the BM25 or metadata legs — so hybrid-side changes
# cannot move these numbers.
# ``reranker_enabled=false`` pins these to the pre-rerank CLIP ordering. The
# reranker default is now profile-aware (``auto`` → GPU-on), so without this
# the snapshot would reorder on a GPU box and defeat the regression-pin intent.
SNAPSHOT_QUERIES: list[dict] = [
    {"q": q, "top_k": 9, "retriever": "clip", "reranker_enabled": "false", "film": SNAPSHOT_FILM}
    for q in ("menina chorando", "1959", "homem na rua")
]


def _snapshot_film_indexed() -> bool:
    """``True`` iff :data:`SNAPSHOT_FILM` is registered with an OK index.

    Deliberately narrower than ``has_indexed_films``: the snapshot pins one
    specific film, so a machine holding a *different* indexed library must
    SKIP rather than fail. Returns ``False`` (so the test SKIPs) on any
    error — a fresh checkout with no models / no embeddings should never
    error the suite, just bow out.
    """
    try:
        from kuaa.library import FilmContext
        from kuaa.search.cache import load_index

        cfg = get_config()
        ctx = FilmContext.for_film(cfg, SNAPSHOT_FILM)
        index = load_index(
            ctx,
            mapping_filename=cfg.embeddings.mapping_filename,
            embeddings_filename=cfg.embeddings.filename,
            cfg=cfg,
        )
        return bool(index.ok)
    except Exception:  # noqa: BLE001 — defensive: any failure → skip
        logger.debug("%s index probe failed; skipping", SNAPSHOT_FILM, exc_info=True)
        return False


@pytest.fixture(scope="module")
def regression_client() -> TestClient:
    """Plain ``TestClient`` against the real config — no ``tmp_config``.

    The snapshot must reflect actual catalogued data; hermetic sandboxing
    would defeat the regression-pin purpose.
    """
    return TestClient(app)


def _scene_ids_from_response(html: str) -> list[int]:
    """Extract scene_ids in render order from the search_results partial.

    Matches the ``data-scene-id="..."`` anchors emitted by
    ``partials/search_results.html``.
    """
    return [int(m) for m in re.findall(r'data-scene-id="(\d+)"', html)]


def _run_query(client: TestClient, query: dict) -> list[int]:
    resp = client.get("/api/search", params=query)
    assert resp.status_code == 200, resp.text
    return _scene_ids_from_response(resp.text)


@pytest.mark.skipif(
    not _snapshot_film_indexed(),
    reason=f"{SNAPSHOT_FILM} not indexed in this env; snapshot requires its real index",
)
def test_prehybrid_snapshot_matches_or_updates(regression_client: TestClient) -> None:
    """Capture or assert the pre-hybrid ``/api/search`` ranking for one film.

    Set ``UPDATE_HYBRID_SNAPSHOT=1`` to regenerate the snapshot against
    the current code. Without the env var the test asserts the
    current ordering still matches the committed snapshot — any drift
    fails loudly with the per-query diff.
    """
    snapshot: dict[str, list[int]] = {}
    for q in SNAPSHOT_QUERIES:
        snapshot[q["q"]] = _run_query(regression_client, q)

    if os.environ.get("UPDATE_HYBRID_SNAPSHOT") == "1":
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n")
        pytest.skip(f"Snapshot updated at {SNAPSHOT_PATH}")

    assert SNAPSHOT_PATH.exists(), (
        "Snapshot missing. Run with UPDATE_HYBRID_SNAPSHOT=1 to regenerate it."
    )
    expected: dict[str, list[int]] = json.loads(SNAPSHOT_PATH.read_text())
    for q, ids in snapshot.items():
        assert ids == expected[q], (
            f"Snapshot drift for query={q!r}: got {ids}, expected {expected[q]}"
        )
