"""Pin pre-M2 /api/search ordering so ?retriever=clip stays byte-for-byte
identical after the hybrid pipeline lands.

The snapshot file is generated by running this test with
``UPDATE_HYBRID_SNAPSHOT=1`` once against pre-M2 main, then committed.
On every subsequent run the test loads the snapshot and asserts the
current ordering still matches. ``?retriever=clip`` must continue to
match this snapshot after the hybrid pipeline ships.

Environment caveat: this test does *not* use the hermetic ``tmp_config``
fixture — the snapshot is meaningful only against a real indexed
library (the maintainer's local Jeca Tatu install at minimum). On CI /
fresh checkouts with no indexed films the test SKIPs cleanly via
:func:`api.services.search.has_indexed_films`. The pinned snapshot
captures behavior against the maintainer's local catalogue at the time
of capture (commit-pinned); see Task A1 in
``docs/superpowers/plans/2026-05-23-hybrid-search.md``.
"""
from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from api.deps import get_config
from api.server import app
from api.services.search import has_indexed_films

logger = logging.getLogger(__name__)

SNAPSHOT_PATH: Path = Path(__file__).parent / "fixtures" / "hybrid_search_regression.json"

# Queries chosen to cover the three behavior buckets the spec calls out:
#  - semantic-strong (CLIP should excel)
#  - literal numeric (BM25 should win once hybrid lands)
#  - generic (broad query, deep ranking matters)
SNAPSHOT_QUERIES: list[dict] = [
    {"q": "menina chorando", "top_k": 9},
    {"q": "1959", "top_k": 9},
    {"q": "homem na rua", "top_k": 9},
]


def _has_indexed_films_available() -> bool:
    """Probe the real (non-hermetic) config for indexed films.

    Returns ``False`` (so the test SKIPs) on any error — a fresh
    checkout with no models / no embeddings should never error the
    suite, just bow out.
    """
    try:
        cfg = get_config()
        return has_indexed_films(cfg)
    except Exception:  # noqa: BLE001 — defensive: any failure → skip
        logger.debug("has_indexed_films probe failed; treating as no films", exc_info=True)
        return False


@pytest.fixture(scope="module")
def regression_client() -> TestClient:
    """Plain ``TestClient`` against the real config — no ``tmp_config``.

    The snapshot must reflect actual catalogued data; hermetic sandboxing
    would defeat the regression-pin purpose.
    """
    return TestClient(app)


def _scene_ids_from_response(html: str) -> list[int]:
    """Extract scene_ids in render order from the search_results partial.

    Matches the ``data-scene-id="..."`` anchors emitted by
    ``partials/search_results.html``.
    """
    return [int(m) for m in re.findall(r'data-scene-id="(\d+)"', html)]


def _run_query(client: TestClient, query: dict) -> list[int]:
    resp = client.get("/api/search", params=query)
    assert resp.status_code == 200, resp.text
    return _scene_ids_from_response(resp.text)


@pytest.mark.skipif(
    not _has_indexed_films_available(),
    reason="no indexed films in test env; snapshot requires real catalogue",
)
def test_pre_m2_snapshot_matches_or_updates(regression_client: TestClient) -> None:
    """Capture or assert the pre-M2 ``/api/search`` ranking.

    Set ``UPDATE_HYBRID_SNAPSHOT=1`` to regenerate the snapshot against
    the current code. Without the env var the test asserts the
    current ordering still matches the committed snapshot — any drift
    fails loudly with the per-query diff.
    """
    snapshot: dict[str, list[int]] = {}
    for q in SNAPSHOT_QUERIES:
        snapshot[q["q"]] = _run_query(regression_client, q)

    if os.environ.get("UPDATE_HYBRID_SNAPSHOT") == "1":
        SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT_PATH.write_text(
            json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n"
        )
        pytest.skip(f"Snapshot updated at {SNAPSHOT_PATH}")

    assert SNAPSHOT_PATH.exists(), (
        "Snapshot missing. Run with UPDATE_HYBRID_SNAPSHOT=1 against pre-M2 main."
    )
    expected: dict[str, list[int]] = json.loads(SNAPSHOT_PATH.read_text())
    for q, ids in snapshot.items():
        assert ids == expected[q], (
            f"Snapshot drift for query={q!r}: got {ids}, expected {expected[q]}"
        )
